window.PORTFOLIO_PUBLICATIONS = [
  {
    title:
      "Evaluating the role of large language models in supporting patient education during the informed consent process for routine radiology procedures",
    authors: [
      "E Einspänner",
      "R Schwab",
      "S Hupfeld",
      "M Thormann",
      "E Fuchs",
      "M Gawlitza",
    ],
    journal: "British Journal of Radiology",
    year: 2025,
    volume: "98 (1176)",
    pages: "2184–2190",
    doi: "10.1093/bjr/tqaf089",
    topics: ["Clinical AI", "LLM", "Patient Education"],
    featured: true,
  },
  {
    title:
      "A multimodal 7T MRI and biomarker study reveals reversible brain changes following acute sleep deprivation",
    authors: [
      "E Einspänner",
      "H Mattern",
      "H Grossmann",
      "E Khadhraoui",
      "SJ Müller",
    ],
    journal: "Sleep Medicine",
    year: 2025,
    doi: "10.1016/j.sleep.2025.108663",
    topics: ["7T MRI", "Biomarkers", "Neuroimaging"],
    featured: true,
  },
  {
    title:
      "Accelerated flat panel computed tomography for pre-operative temporal bone imaging: image quality and dosimetry comparison to conventional high resolution multislice computed tomography",
    authors: [
      "E Diamandis",
      "SJ Müller",
      "E Khadhraoui",
      "S Klebingat",
      "E Einspänner",
    ],
    journal: "Neuroradiology",
    year: 2025,
    volume: "67 (7)",
    pages: "1925–1934",
    doi: "10.1007/s00234-025-03389-7",
    topics: ["CT", "Medical Imaging", "Dosimetry"],
    featured: true,
  },
  {
    title: "Local brain volume reductions in patients with non-lesional epilepsy on 7T MRI",
    authors: [
      "J Schwarzer",
      "E Khadhraoui",
      "E Einspänner",
      "O Kukhlenko",
      "D Behme",
    ],
    journal: "Neuroradiology",
    year: 2025,
    doi: "10.1007/s00234-025-03345-5",
    topics: ["7T MRI", "Epilepsy", "Brain Volumetry"],
    featured: true,
  },
  {
    title:
      "Comparison of brain volumetry in patients with non-lesional epilepsy on 3 and 7 T MPRAGE",
    authors: [
      "J Schwarzer",
      "E Khadhraoui",
      "E Einspänner",
      "O Kukhlenko",
      "D Behme",
    ],
    journal: "Quantitative Imaging in Medicine and Surgery",
    year: 2025,
    volume: "15 (11)",
    pages: "11408–11426",
    doi: "10.21037/qims-25-456",
    topics: ["7T MRI", "Epilepsy", "Volumetry"],
    featured: false,
  },
  {
    title:
      "Calculation of virtual 3D subtraction angiographies using conditional generative adversarial networks (cGANs)",
    authors: [
      "SJ Müller",
      "E Einspänner",
      "S Klebingat",
      "S Zubel",
      "R Schwab",
      "E Fuchs",
    ],
    journal: "BMC Medical Imaging",
    year: 2024,
    volume: "24 (1)",
    pages: "276",
    doi: "10.1186/s12880-024-01454-7",
    topics: ["Deep Learning", "cGAN", "Angiography"],
    featured: true,
  },
  {
    title:
      "Quantifying radionuclide residues in hospital wastewater: a case study on [131I]I and [177mLu]Lu/[177Lu]Lu",
    authors: [
      "D Kupitz",
      "E Einspänner",
      "H Wissel",
      "M Volk",
      "A Hohn",
      "MC Kreissl",
    ],
    journal: "Medical Physics",
    year: 2024,
    volume: "51 (10)",
    pages: "7574–7579",
    doi: "10.1002/mp.18123",
    topics: ["Nuclear Medicine", "Radiation", "Medical Physics"],
    featured: false,
  },
  {
    title:
      "Assessment of radiation measurement devices for the detection of [177Lu]Lu-labeled radiopharmaceuticals containing [177mLu]Lu-impurities",
    authors: [
      "D Kupitz",
      "E Einspänner",
      "H Wissel",
      "A Hohn",
      "MC Kreissl",
      "OS Grosser",
    ],
    journal: "Medical Physics",
    year: 2023,
    volume: "50 (1)",
    pages: "590–599",
    doi: "10.1002/mp.16089",
    topics: ["Nuclear Medicine", "Radiation", "Medical Physics"],
    featured: true,
  },
  {
    title:
      "Evaluating different methods of MR-based motion correction in simultaneous PET/MR using a head phantom moved by a robotic system",
    authors: [
      "E Einspänner",
      "TH Jochimsen",
      "J Harries",
      "A Melzer",
      "M Unger",
      "R Brown",
    ],
    journal: "EJNMMI Physics",
    year: 2022,
    volume: "9 (1)",
    pages: "15",
    doi: "10.1186/s40658-022-00450-4",
    topics: ["PET/MR", "Motion Correction", "Medical Physics"],
    featured: true,
  },
  {
    title:
      "Evaluation of novel methods for motion correction in simultaneous PET/MR",
    authors: [
      "E Einspänner",
      "T Jochimsen",
      "A Melzer",
      "M Unger",
      "R Brown",
      "K Thielemans",
    ],
    journal: "IEEE NSS/MIC Conference Proceedings",
    year: 2020,
    topics: ["PET/MR", "Motion Correction", "Conference"],
    featured: false,
  },
];
