/**
 * Tech stack pyramid — rows taper from top (widest) to bottom.
 * Icons via Simple Icons CDN (https://simpleicons.org).
 */
window.PORTFOLIO_TECH_STACK = [
  [
    { name: "Python", icon: "python" },
    { name: "JavaScript", icon: "javascript" },
    { name: "TypeScript", icon: "typescript" },
    { name: "C", icon: "c" },
    { name: "C++", icon: "cplusplus" },
    { name: "C#", abbr: "C#" },
    { name: "Kotlin", icon: "kotlin" },
    { name: "HTML", icon: "html5" },
    { name: "CSS", icon: "css3" },
    { name: "Bash", icon: "gnubash" },
    { name: "React", icon: "react" },
    { name: "Next.js", icon: "nextdotjs" },
  ],
  [
    { name: "Bootstrap", icon: "bootstrap" },
    { name: "Node.js", icon: "nodedotjs" },
    { name: "Django", icon: "django" },
    { name: "Flask", icon: "flask" },
    { name: "FastAPI", icon: "fastapi" },
    { name: "Tailwind CSS", icon: "tailwindcss" },
    { name: "LangChain", icon: "langchain" },
    { name: "TensorFlow", icon: "tensorflow" },
    { name: "PyTorch", icon: "pytorch" },
    { name: "Keras", icon: "keras" },
    { name: "scikit-learn", icon: "scikitlearn" },
    { name: "OpenCV", icon: "opencv" },
  ],
  [
    { name: "NumPy", icon: "numpy" },
    { name: "Pandas", icon: "pandas" },
    { name: "Matplotlib", abbr: "Mpl" },
    { name: "R", icon: "r" },
    { name: "PostgreSQL", icon: "postgresql" },
    { name: "Supabase", icon: "supabase" },
    { name: "MySQL", icon: "mysql" },
    { name: "MongoDB", icon: "mongodb" },
    { name: "Firebase", icon: "firebase" },
    { name: "Redis", icon: "redis" },
    { name: "GraphQL", icon: "graphql" },
    { name: "Docker", icon: "docker" },
  ],
  [
    { name: "Podman", icon: "podman" },
    { name: "Kubernetes", icon: "kubernetes" },
    { name: "Proxmox", icon: "proxmox" },
    { name: "Azure", icon: "microsoftazure" },
    { name: "AWS", icon: "amazonaws" },
    { name: "Git", icon: "git" },
    { name: "GitHub", icon: "github" },
    { name: "Linux", icon: "linux" },
    { name: "macOS", icon: "apple" },
    { name: "Windows", icon: "windows" },
    { name: "Android", icon: "android" },
    { name: "VS Code", icon: "visualstudiocode" },
  ],
  [
    { name: "Cursor", icon: "cursor" },
    { name: "Vercel", icon: "vercel" },
    { name: "Netlify", icon: "netlify" },
    { name: "Jupyter", icon: "jupyter" },
    { name: "Claude Code", icon: "anthropic" },
    { name: "Codex", abbr: "Cx" },
    { name: "n8n", icon: "n8n" },
    { name: "Figma", icon: "figma" },
    { name: "Postman", icon: "postman" },
    { name: "Insomnia", icon: "insomnia" },
    { name: "LaTeX", icon: "latex" },
    { name: "Hugging Face", icon: "huggingface" },
  ],
  [
    { name: "MS Office", abbr: "Of" },
    { name: "Photoshop", abbr: "Ps" },
  ],
];
